name: obd
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - scipy
  - sympy
  - mpmath
  - numba
  - matplotlib
  - plotly
  - scikit-learn
  - umap-learn
  - pip
  - pip:
      - obd-core @ git+https://github.com/dperlman/OBD-core.git@v0.1.0
